<?php
/**
 * PatchEnvironmentCompose202Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.15.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace QuantClient\Model;

use \ArrayAccess;
use \QuantClient\ObjectSerializer;

/**
 * PatchEnvironmentCompose202Response Class Doc Comment
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PatchEnvironmentCompose202Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'patchEnvironmentCompose_202_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'architecture' => 'string',
        'task_cpu' => 'string',
        'task_memory' => 'string',
        'min_capacity' => 'int',
        'max_capacity' => 'int',
        'containers' => 'object[]',
        'spot_configuration' => '\QuantClient\Model\PatchEnvironmentCompose202ResponseSpotConfiguration',
        'enable_cross_env_networking' => 'bool',
        'enable_cross_app_networking' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'architecture' => null,
        'task_cpu' => null,
        'task_memory' => null,
        'min_capacity' => null,
        'max_capacity' => null,
        'containers' => null,
        'spot_configuration' => null,
        'enable_cross_env_networking' => null,
        'enable_cross_app_networking' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'architecture' => false,
        'task_cpu' => false,
        'task_memory' => false,
        'min_capacity' => false,
        'max_capacity' => false,
        'containers' => false,
        'spot_configuration' => false,
        'enable_cross_env_networking' => false,
        'enable_cross_app_networking' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'architecture' => 'architecture',
        'task_cpu' => 'taskCpu',
        'task_memory' => 'taskMemory',
        'min_capacity' => 'minCapacity',
        'max_capacity' => 'maxCapacity',
        'containers' => 'containers',
        'spot_configuration' => 'spotConfiguration',
        'enable_cross_env_networking' => 'enableCrossEnvNetworking',
        'enable_cross_app_networking' => 'enableCrossAppNetworking'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'architecture' => 'setArchitecture',
        'task_cpu' => 'setTaskCpu',
        'task_memory' => 'setTaskMemory',
        'min_capacity' => 'setMinCapacity',
        'max_capacity' => 'setMaxCapacity',
        'containers' => 'setContainers',
        'spot_configuration' => 'setSpotConfiguration',
        'enable_cross_env_networking' => 'setEnableCrossEnvNetworking',
        'enable_cross_app_networking' => 'setEnableCrossAppNetworking'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'architecture' => 'getArchitecture',
        'task_cpu' => 'getTaskCpu',
        'task_memory' => 'getTaskMemory',
        'min_capacity' => 'getMinCapacity',
        'max_capacity' => 'getMaxCapacity',
        'containers' => 'getContainers',
        'spot_configuration' => 'getSpotConfiguration',
        'enable_cross_env_networking' => 'getEnableCrossEnvNetworking',
        'enable_cross_app_networking' => 'getEnableCrossAppNetworking'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('architecture', $data ?? [], null);
        $this->setIfExists('task_cpu', $data ?? [], null);
        $this->setIfExists('task_memory', $data ?? [], null);
        $this->setIfExists('min_capacity', $data ?? [], null);
        $this->setIfExists('max_capacity', $data ?? [], null);
        $this->setIfExists('containers', $data ?? [], null);
        $this->setIfExists('spot_configuration', $data ?? [], null);
        $this->setIfExists('enable_cross_env_networking', $data ?? [], null);
        $this->setIfExists('enable_cross_app_networking', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets architecture
     *
     * @return string|null
     */
    public function getArchitecture()
    {
        return $this->container['architecture'];
    }

    /**
     * Sets architecture
     *
     * @param string|null $architecture architecture
     *
     * @return self
     */
    public function setArchitecture($architecture)
    {
        if (is_null($architecture)) {
            throw new \InvalidArgumentException('non-nullable architecture cannot be null');
        }
        $this->container['architecture'] = $architecture;

        return $this;
    }

    /**
     * Gets task_cpu
     *
     * @return string|null
     */
    public function getTaskCpu()
    {
        return $this->container['task_cpu'];
    }

    /**
     * Sets task_cpu
     *
     * @param string|null $task_cpu task_cpu
     *
     * @return self
     */
    public function setTaskCpu($task_cpu)
    {
        if (is_null($task_cpu)) {
            throw new \InvalidArgumentException('non-nullable task_cpu cannot be null');
        }
        $this->container['task_cpu'] = $task_cpu;

        return $this;
    }

    /**
     * Gets task_memory
     *
     * @return string|null
     */
    public function getTaskMemory()
    {
        return $this->container['task_memory'];
    }

    /**
     * Sets task_memory
     *
     * @param string|null $task_memory task_memory
     *
     * @return self
     */
    public function setTaskMemory($task_memory)
    {
        if (is_null($task_memory)) {
            throw new \InvalidArgumentException('non-nullable task_memory cannot be null');
        }
        $this->container['task_memory'] = $task_memory;

        return $this;
    }

    /**
     * Gets min_capacity
     *
     * @return int|null
     */
    public function getMinCapacity()
    {
        return $this->container['min_capacity'];
    }

    /**
     * Sets min_capacity
     *
     * @param int|null $min_capacity min_capacity
     *
     * @return self
     */
    public function setMinCapacity($min_capacity)
    {
        if (is_null($min_capacity)) {
            throw new \InvalidArgumentException('non-nullable min_capacity cannot be null');
        }
        $this->container['min_capacity'] = $min_capacity;

        return $this;
    }

    /**
     * Gets max_capacity
     *
     * @return int|null
     */
    public function getMaxCapacity()
    {
        return $this->container['max_capacity'];
    }

    /**
     * Sets max_capacity
     *
     * @param int|null $max_capacity max_capacity
     *
     * @return self
     */
    public function setMaxCapacity($max_capacity)
    {
        if (is_null($max_capacity)) {
            throw new \InvalidArgumentException('non-nullable max_capacity cannot be null');
        }
        $this->container['max_capacity'] = $max_capacity;

        return $this;
    }

    /**
     * Gets containers
     *
     * @return object[]|null
     */
    public function getContainers()
    {
        return $this->container['containers'];
    }

    /**
     * Sets containers
     *
     * @param object[]|null $containers containers
     *
     * @return self
     */
    public function setContainers($containers)
    {
        if (is_null($containers)) {
            throw new \InvalidArgumentException('non-nullable containers cannot be null');
        }
        $this->container['containers'] = $containers;

        return $this;
    }

    /**
     * Gets spot_configuration
     *
     * @return \QuantClient\Model\PatchEnvironmentCompose202ResponseSpotConfiguration|null
     */
    public function getSpotConfiguration()
    {
        return $this->container['spot_configuration'];
    }

    /**
     * Sets spot_configuration
     *
     * @param \QuantClient\Model\PatchEnvironmentCompose202ResponseSpotConfiguration|null $spot_configuration spot_configuration
     *
     * @return self
     */
    public function setSpotConfiguration($spot_configuration)
    {
        if (is_null($spot_configuration)) {
            throw new \InvalidArgumentException('non-nullable spot_configuration cannot be null');
        }
        $this->container['spot_configuration'] = $spot_configuration;

        return $this;
    }

    /**
     * Gets enable_cross_env_networking
     *
     * @return bool|null
     */
    public function getEnableCrossEnvNetworking()
    {
        return $this->container['enable_cross_env_networking'];
    }

    /**
     * Sets enable_cross_env_networking
     *
     * @param bool|null $enable_cross_env_networking enable_cross_env_networking
     *
     * @return self
     */
    public function setEnableCrossEnvNetworking($enable_cross_env_networking)
    {
        if (is_null($enable_cross_env_networking)) {
            throw new \InvalidArgumentException('non-nullable enable_cross_env_networking cannot be null');
        }
        $this->container['enable_cross_env_networking'] = $enable_cross_env_networking;

        return $this;
    }

    /**
     * Gets enable_cross_app_networking
     *
     * @return bool|null
     */
    public function getEnableCrossAppNetworking()
    {
        return $this->container['enable_cross_app_networking'];
    }

    /**
     * Sets enable_cross_app_networking
     *
     * @param bool|null $enable_cross_app_networking enable_cross_app_networking
     *
     * @return self
     */
    public function setEnableCrossAppNetworking($enable_cross_app_networking)
    {
        if (is_null($enable_cross_app_networking)) {
            throw new \InvalidArgumentException('non-nullable enable_cross_app_networking cannot be null');
        }
        $this->container['enable_cross_app_networking'] = $enable_cross_app_networking;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


