<?php
/**
 * V1Meta
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.12.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace QuantClient\Model;

use \ArrayAccess;
use \QuantClient\ObjectSerializer;

/**
 * V1Meta Class Doc Comment
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1Meta implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'V1Meta';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'url' => 'string',
        'type' => 'string',
        'seq_num' => 'int',
        'published' => 'bool',
        'published_revision' => 'int',
        'published_md5' => 'string',
        'byte_length' => 'int',
        'revision_count' => 'int',
        'highest_revision_number' => 'int',
        'deleted' => 'bool',
        'deleted_timestamp' => 'int',
        'md5' => 'string',
        'revision_number' => 'int',
        'date_timestamp' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'url' => null,
        'type' => null,
        'seq_num' => null,
        'published' => null,
        'published_revision' => null,
        'published_md5' => null,
        'byte_length' => null,
        'revision_count' => null,
        'highest_revision_number' => null,
        'deleted' => null,
        'deleted_timestamp' => null,
        'md5' => null,
        'revision_number' => null,
        'date_timestamp' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'url' => false,
        'type' => false,
        'seq_num' => false,
        'published' => false,
        'published_revision' => false,
        'published_md5' => false,
        'byte_length' => false,
        'revision_count' => false,
        'highest_revision_number' => false,
        'deleted' => false,
        'deleted_timestamp' => false,
        'md5' => false,
        'revision_number' => false,
        'date_timestamp' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'url' => 'url',
        'type' => 'type',
        'seq_num' => 'seq_num',
        'published' => 'published',
        'published_revision' => 'published_revision',
        'published_md5' => 'published_md5',
        'byte_length' => 'byte_length',
        'revision_count' => 'revision_count',
        'highest_revision_number' => 'highest_revision_number',
        'deleted' => 'deleted',
        'deleted_timestamp' => 'deleted_timestamp',
        'md5' => 'md5',
        'revision_number' => 'revision_number',
        'date_timestamp' => 'date_timestamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'url' => 'setUrl',
        'type' => 'setType',
        'seq_num' => 'setSeqNum',
        'published' => 'setPublished',
        'published_revision' => 'setPublishedRevision',
        'published_md5' => 'setPublishedMd5',
        'byte_length' => 'setByteLength',
        'revision_count' => 'setRevisionCount',
        'highest_revision_number' => 'setHighestRevisionNumber',
        'deleted' => 'setDeleted',
        'deleted_timestamp' => 'setDeletedTimestamp',
        'md5' => 'setMd5',
        'revision_number' => 'setRevisionNumber',
        'date_timestamp' => 'setDateTimestamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'url' => 'getUrl',
        'type' => 'getType',
        'seq_num' => 'getSeqNum',
        'published' => 'getPublished',
        'published_revision' => 'getPublishedRevision',
        'published_md5' => 'getPublishedMd5',
        'byte_length' => 'getByteLength',
        'revision_count' => 'getRevisionCount',
        'highest_revision_number' => 'getHighestRevisionNumber',
        'deleted' => 'getDeleted',
        'deleted_timestamp' => 'getDeletedTimestamp',
        'md5' => 'getMd5',
        'revision_number' => 'getRevisionNumber',
        'date_timestamp' => 'getDateTimestamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('seq_num', $data ?? [], null);
        $this->setIfExists('published', $data ?? [], null);
        $this->setIfExists('published_revision', $data ?? [], null);
        $this->setIfExists('published_md5', $data ?? [], null);
        $this->setIfExists('byte_length', $data ?? [], null);
        $this->setIfExists('revision_count', $data ?? [], null);
        $this->setIfExists('highest_revision_number', $data ?? [], null);
        $this->setIfExists('deleted', $data ?? [], null);
        $this->setIfExists('deleted_timestamp', $data ?? [], null);
        $this->setIfExists('md5', $data ?? [], null);
        $this->setIfExists('revision_number', $data ?? [], null);
        $this->setIfExists('date_timestamp', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets seq_num
     *
     * @return int|null
     */
    public function getSeqNum()
    {
        return $this->container['seq_num'];
    }

    /**
     * Sets seq_num
     *
     * @param int|null $seq_num seq_num
     *
     * @return self
     */
    public function setSeqNum($seq_num)
    {
        if (is_null($seq_num)) {
            throw new \InvalidArgumentException('non-nullable seq_num cannot be null');
        }
        $this->container['seq_num'] = $seq_num;

        return $this;
    }

    /**
     * Gets published
     *
     * @return bool|null
     */
    public function getPublished()
    {
        return $this->container['published'];
    }

    /**
     * Sets published
     *
     * @param bool|null $published published
     *
     * @return self
     */
    public function setPublished($published)
    {
        if (is_null($published)) {
            throw new \InvalidArgumentException('non-nullable published cannot be null');
        }
        $this->container['published'] = $published;

        return $this;
    }

    /**
     * Gets published_revision
     *
     * @return int|null
     */
    public function getPublishedRevision()
    {
        return $this->container['published_revision'];
    }

    /**
     * Sets published_revision
     *
     * @param int|null $published_revision published_revision
     *
     * @return self
     */
    public function setPublishedRevision($published_revision)
    {
        if (is_null($published_revision)) {
            throw new \InvalidArgumentException('non-nullable published_revision cannot be null');
        }
        $this->container['published_revision'] = $published_revision;

        return $this;
    }

    /**
     * Gets published_md5
     *
     * @return string|null
     */
    public function getPublishedMd5()
    {
        return $this->container['published_md5'];
    }

    /**
     * Sets published_md5
     *
     * @param string|null $published_md5 published_md5
     *
     * @return self
     */
    public function setPublishedMd5($published_md5)
    {
        if (is_null($published_md5)) {
            throw new \InvalidArgumentException('non-nullable published_md5 cannot be null');
        }
        $this->container['published_md5'] = $published_md5;

        return $this;
    }

    /**
     * Gets byte_length
     *
     * @return int|null
     */
    public function getByteLength()
    {
        return $this->container['byte_length'];
    }

    /**
     * Sets byte_length
     *
     * @param int|null $byte_length byte_length
     *
     * @return self
     */
    public function setByteLength($byte_length)
    {
        if (is_null($byte_length)) {
            throw new \InvalidArgumentException('non-nullable byte_length cannot be null');
        }
        $this->container['byte_length'] = $byte_length;

        return $this;
    }

    /**
     * Gets revision_count
     *
     * @return int|null
     */
    public function getRevisionCount()
    {
        return $this->container['revision_count'];
    }

    /**
     * Sets revision_count
     *
     * @param int|null $revision_count revision_count
     *
     * @return self
     */
    public function setRevisionCount($revision_count)
    {
        if (is_null($revision_count)) {
            throw new \InvalidArgumentException('non-nullable revision_count cannot be null');
        }
        $this->container['revision_count'] = $revision_count;

        return $this;
    }

    /**
     * Gets highest_revision_number
     *
     * @return int|null
     */
    public function getHighestRevisionNumber()
    {
        return $this->container['highest_revision_number'];
    }

    /**
     * Sets highest_revision_number
     *
     * @param int|null $highest_revision_number highest_revision_number
     *
     * @return self
     */
    public function setHighestRevisionNumber($highest_revision_number)
    {
        if (is_null($highest_revision_number)) {
            throw new \InvalidArgumentException('non-nullable highest_revision_number cannot be null');
        }
        $this->container['highest_revision_number'] = $highest_revision_number;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool|null $deleted deleted
     *
     * @return self
     */
    public function setDeleted($deleted)
    {
        if (is_null($deleted)) {
            throw new \InvalidArgumentException('non-nullable deleted cannot be null');
        }
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets deleted_timestamp
     *
     * @return int|null
     */
    public function getDeletedTimestamp()
    {
        return $this->container['deleted_timestamp'];
    }

    /**
     * Sets deleted_timestamp
     *
     * @param int|null $deleted_timestamp deleted_timestamp
     *
     * @return self
     */
    public function setDeletedTimestamp($deleted_timestamp)
    {
        if (is_null($deleted_timestamp)) {
            throw new \InvalidArgumentException('non-nullable deleted_timestamp cannot be null');
        }
        $this->container['deleted_timestamp'] = $deleted_timestamp;

        return $this;
    }

    /**
     * Gets md5
     *
     * @return string|null
     */
    public function getMd5()
    {
        return $this->container['md5'];
    }

    /**
     * Sets md5
     *
     * @param string|null $md5 md5
     *
     * @return self
     */
    public function setMd5($md5)
    {
        if (is_null($md5)) {
            throw new \InvalidArgumentException('non-nullable md5 cannot be null');
        }
        $this->container['md5'] = $md5;

        return $this;
    }

    /**
     * Gets revision_number
     *
     * @return int|null
     */
    public function getRevisionNumber()
    {
        return $this->container['revision_number'];
    }

    /**
     * Sets revision_number
     *
     * @param int|null $revision_number revision_number
     *
     * @return self
     */
    public function setRevisionNumber($revision_number)
    {
        if (is_null($revision_number)) {
            throw new \InvalidArgumentException('non-nullable revision_number cannot be null');
        }
        $this->container['revision_number'] = $revision_number;

        return $this;
    }

    /**
     * Gets date_timestamp
     *
     * @return int|null
     */
    public function getDateTimestamp()
    {
        return $this->container['date_timestamp'];
    }

    /**
     * Sets date_timestamp
     *
     * @param int|null $date_timestamp date_timestamp
     *
     * @return self
     */
    public function setDateTimestamp($date_timestamp)
    {
        if (is_null($date_timestamp)) {
            throw new \InvalidArgumentException('non-nullable date_timestamp cannot be null');
        }
        $this->container['date_timestamp'] = $date_timestamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


