<?php
/**
 * V2RuleProxyRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace QuantClient\Model;

use \ArrayAccess;
use \QuantClient\ObjectSerializer;

/**
 * V2RuleProxyRequest Class Doc Comment
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V2RuleProxyRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'V2RuleProxyRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'domain' => 'string[]',
        'name' => 'string',
        'uuid' => 'string',
        'weight' => 'int',
        'disabled' => 'bool',
        'url' => 'string[]',
        'country' => 'string',
        'country_is' => 'string[]',
        'country_is_not' => 'string[]',
        'method' => 'string',
        'method_is' => 'string[]',
        'method_is_not' => 'string[]',
        'ip' => 'string',
        'ip_is' => 'string[]',
        'ip_is_not' => 'string[]',
        'to' => 'string',
        'host' => 'string',
        'auth_user' => 'string',
        'auth_pass' => 'string',
        'disable_ssl_verify' => 'bool',
        'cache_lifetime' => 'string',
        'only_proxy_404' => 'bool',
        'inject_headers' => 'array<string,string>',
        'proxy_strip_headers' => 'string[]',
        'proxy_strip_request_headers' => 'string[]',
        'origin_timeout' => 'string',
        'failover_mode' => 'bool',
        'failover_origin_ttfb' => 'string',
        'failover_origin_status_codes' => 'string[]',
        'failover_lifetime' => 'string',
        'proxy_alert_enabled' => 'bool',
        'waf_enabled' => 'bool',
        'waf_config' => '\QuantClient\Model\WafConfig',
        'application_proxy' => 'bool',
        'application_name' => 'string',
        'application_environment' => 'string',
        'application_container' => 'string',
        'application_port' => 'int',
        'static_error_page' => 'string',
        'static_error_page_status_codes' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'domain' => null,
        'name' => null,
        'uuid' => null,
        'weight' => null,
        'disabled' => null,
        'url' => null,
        'country' => null,
        'country_is' => null,
        'country_is_not' => null,
        'method' => null,
        'method_is' => null,
        'method_is_not' => null,
        'ip' => null,
        'ip_is' => null,
        'ip_is_not' => null,
        'to' => null,
        'host' => null,
        'auth_user' => null,
        'auth_pass' => null,
        'disable_ssl_verify' => null,
        'cache_lifetime' => null,
        'only_proxy_404' => null,
        'inject_headers' => null,
        'proxy_strip_headers' => null,
        'proxy_strip_request_headers' => null,
        'origin_timeout' => null,
        'failover_mode' => null,
        'failover_origin_ttfb' => null,
        'failover_origin_status_codes' => null,
        'failover_lifetime' => null,
        'proxy_alert_enabled' => null,
        'waf_enabled' => null,
        'waf_config' => null,
        'application_proxy' => null,
        'application_name' => null,
        'application_environment' => null,
        'application_container' => null,
        'application_port' => null,
        'static_error_page' => null,
        'static_error_page_status_codes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'domain' => false,
        'name' => false,
        'uuid' => false,
        'weight' => false,
        'disabled' => false,
        'url' => false,
        'country' => false,
        'country_is' => false,
        'country_is_not' => false,
        'method' => false,
        'method_is' => false,
        'method_is_not' => false,
        'ip' => false,
        'ip_is' => false,
        'ip_is_not' => false,
        'to' => false,
        'host' => false,
        'auth_user' => false,
        'auth_pass' => false,
        'disable_ssl_verify' => false,
        'cache_lifetime' => true,
        'only_proxy_404' => false,
        'inject_headers' => true,
        'proxy_strip_headers' => false,
        'proxy_strip_request_headers' => false,
        'origin_timeout' => false,
        'failover_mode' => false,
        'failover_origin_ttfb' => false,
        'failover_origin_status_codes' => false,
        'failover_lifetime' => false,
        'proxy_alert_enabled' => false,
        'waf_enabled' => false,
        'waf_config' => true,
        'application_proxy' => false,
        'application_name' => false,
        'application_environment' => false,
        'application_container' => false,
        'application_port' => false,
        'static_error_page' => true,
        'static_error_page_status_codes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'domain' => 'domain',
        'name' => 'name',
        'uuid' => 'uuid',
        'weight' => 'weight',
        'disabled' => 'disabled',
        'url' => 'url',
        'country' => 'country',
        'country_is' => 'country_is',
        'country_is_not' => 'country_is_not',
        'method' => 'method',
        'method_is' => 'method_is',
        'method_is_not' => 'method_is_not',
        'ip' => 'ip',
        'ip_is' => 'ip_is',
        'ip_is_not' => 'ip_is_not',
        'to' => 'to',
        'host' => 'host',
        'auth_user' => 'auth_user',
        'auth_pass' => 'auth_pass',
        'disable_ssl_verify' => 'disable_ssl_verify',
        'cache_lifetime' => 'cache_lifetime',
        'only_proxy_404' => 'only_proxy_404',
        'inject_headers' => 'inject_headers',
        'proxy_strip_headers' => 'proxy_strip_headers',
        'proxy_strip_request_headers' => 'proxy_strip_request_headers',
        'origin_timeout' => 'origin_timeout',
        'failover_mode' => 'failover_mode',
        'failover_origin_ttfb' => 'failover_origin_ttfb',
        'failover_origin_status_codes' => 'failover_origin_status_codes',
        'failover_lifetime' => 'failover_lifetime',
        'proxy_alert_enabled' => 'proxy_alert_enabled',
        'waf_enabled' => 'waf_enabled',
        'waf_config' => 'waf_config',
        'application_proxy' => 'application_proxy',
        'application_name' => 'application_name',
        'application_environment' => 'application_environment',
        'application_container' => 'application_container',
        'application_port' => 'application_port',
        'static_error_page' => 'static_error_page',
        'static_error_page_status_codes' => 'static_error_page_status_codes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'domain' => 'setDomain',
        'name' => 'setName',
        'uuid' => 'setUuid',
        'weight' => 'setWeight',
        'disabled' => 'setDisabled',
        'url' => 'setUrl',
        'country' => 'setCountry',
        'country_is' => 'setCountryIs',
        'country_is_not' => 'setCountryIsNot',
        'method' => 'setMethod',
        'method_is' => 'setMethodIs',
        'method_is_not' => 'setMethodIsNot',
        'ip' => 'setIp',
        'ip_is' => 'setIpIs',
        'ip_is_not' => 'setIpIsNot',
        'to' => 'setTo',
        'host' => 'setHost',
        'auth_user' => 'setAuthUser',
        'auth_pass' => 'setAuthPass',
        'disable_ssl_verify' => 'setDisableSslVerify',
        'cache_lifetime' => 'setCacheLifetime',
        'only_proxy_404' => 'setOnlyProxy404',
        'inject_headers' => 'setInjectHeaders',
        'proxy_strip_headers' => 'setProxyStripHeaders',
        'proxy_strip_request_headers' => 'setProxyStripRequestHeaders',
        'origin_timeout' => 'setOriginTimeout',
        'failover_mode' => 'setFailoverMode',
        'failover_origin_ttfb' => 'setFailoverOriginTtfb',
        'failover_origin_status_codes' => 'setFailoverOriginStatusCodes',
        'failover_lifetime' => 'setFailoverLifetime',
        'proxy_alert_enabled' => 'setProxyAlertEnabled',
        'waf_enabled' => 'setWafEnabled',
        'waf_config' => 'setWafConfig',
        'application_proxy' => 'setApplicationProxy',
        'application_name' => 'setApplicationName',
        'application_environment' => 'setApplicationEnvironment',
        'application_container' => 'setApplicationContainer',
        'application_port' => 'setApplicationPort',
        'static_error_page' => 'setStaticErrorPage',
        'static_error_page_status_codes' => 'setStaticErrorPageStatusCodes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'domain' => 'getDomain',
        'name' => 'getName',
        'uuid' => 'getUuid',
        'weight' => 'getWeight',
        'disabled' => 'getDisabled',
        'url' => 'getUrl',
        'country' => 'getCountry',
        'country_is' => 'getCountryIs',
        'country_is_not' => 'getCountryIsNot',
        'method' => 'getMethod',
        'method_is' => 'getMethodIs',
        'method_is_not' => 'getMethodIsNot',
        'ip' => 'getIp',
        'ip_is' => 'getIpIs',
        'ip_is_not' => 'getIpIsNot',
        'to' => 'getTo',
        'host' => 'getHost',
        'auth_user' => 'getAuthUser',
        'auth_pass' => 'getAuthPass',
        'disable_ssl_verify' => 'getDisableSslVerify',
        'cache_lifetime' => 'getCacheLifetime',
        'only_proxy_404' => 'getOnlyProxy404',
        'inject_headers' => 'getInjectHeaders',
        'proxy_strip_headers' => 'getProxyStripHeaders',
        'proxy_strip_request_headers' => 'getProxyStripRequestHeaders',
        'origin_timeout' => 'getOriginTimeout',
        'failover_mode' => 'getFailoverMode',
        'failover_origin_ttfb' => 'getFailoverOriginTtfb',
        'failover_origin_status_codes' => 'getFailoverOriginStatusCodes',
        'failover_lifetime' => 'getFailoverLifetime',
        'proxy_alert_enabled' => 'getProxyAlertEnabled',
        'waf_enabled' => 'getWafEnabled',
        'waf_config' => 'getWafConfig',
        'application_proxy' => 'getApplicationProxy',
        'application_name' => 'getApplicationName',
        'application_environment' => 'getApplicationEnvironment',
        'application_container' => 'getApplicationContainer',
        'application_port' => 'getApplicationPort',
        'static_error_page' => 'getStaticErrorPage',
        'static_error_page_status_codes' => 'getStaticErrorPageStatusCodes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('weight', $data ?? [], 0);
        $this->setIfExists('disabled', $data ?? [], false);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('country_is', $data ?? [], null);
        $this->setIfExists('country_is_not', $data ?? [], null);
        $this->setIfExists('method', $data ?? [], null);
        $this->setIfExists('method_is', $data ?? [], null);
        $this->setIfExists('method_is_not', $data ?? [], null);
        $this->setIfExists('ip', $data ?? [], null);
        $this->setIfExists('ip_is', $data ?? [], null);
        $this->setIfExists('ip_is_not', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('auth_user', $data ?? [], '');
        $this->setIfExists('auth_pass', $data ?? [], '');
        $this->setIfExists('disable_ssl_verify', $data ?? [], false);
        $this->setIfExists('cache_lifetime', $data ?? [], null);
        $this->setIfExists('only_proxy_404', $data ?? [], false);
        $this->setIfExists('inject_headers', $data ?? [], null);
        $this->setIfExists('proxy_strip_headers', $data ?? [], null);
        $this->setIfExists('proxy_strip_request_headers', $data ?? [], null);
        $this->setIfExists('origin_timeout', $data ?? [], null);
        $this->setIfExists('failover_mode', $data ?? [], false);
        $this->setIfExists('failover_origin_ttfb', $data ?? [], '2000');
        $this->setIfExists('failover_origin_status_codes', $data ?? [], null);
        $this->setIfExists('failover_lifetime', $data ?? [], '300');
        $this->setIfExists('proxy_alert_enabled', $data ?? [], false);
        $this->setIfExists('waf_enabled', $data ?? [], false);
        $this->setIfExists('waf_config', $data ?? [], null);
        $this->setIfExists('application_proxy', $data ?? [], false);
        $this->setIfExists('application_name', $data ?? [], null);
        $this->setIfExists('application_environment', $data ?? [], null);
        $this->setIfExists('application_container', $data ?? [], null);
        $this->setIfExists('application_port', $data ?? [], null);
        $this->setIfExists('static_error_page', $data ?? [], null);
        $this->setIfExists('static_error_page_status_codes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets domain
     *
     * @return string[]
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string[] $domain Domain patterns (default: any)
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Rule name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid Rule UUID
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return int|null
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param int|null $weight Rule weight
     *
     * @return self
     */
    public function setWeight($weight)
    {
        if (is_null($weight)) {
            throw new \InvalidArgumentException('non-nullable weight cannot be null');
        }
        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets disabled
     *
     * @return bool|null
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param bool|null $disabled Whether rule is disabled
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        if (is_null($disabled)) {
            throw new \InvalidArgumentException('non-nullable disabled cannot be null');
        }
        $this->container['disabled'] = $disabled;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string[]
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string[] $url URL patterns
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Country filter type (country_is, country_is_not, any)
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets country_is
     *
     * @return string[]|null
     */
    public function getCountryIs()
    {
        return $this->container['country_is'];
    }

    /**
     * Sets country_is
     *
     * @param string[]|null $country_is Allowed countries
     *
     * @return self
     */
    public function setCountryIs($country_is)
    {
        if (is_null($country_is)) {
            throw new \InvalidArgumentException('non-nullable country_is cannot be null');
        }
        $this->container['country_is'] = $country_is;

        return $this;
    }

    /**
     * Gets country_is_not
     *
     * @return string[]|null
     */
    public function getCountryIsNot()
    {
        return $this->container['country_is_not'];
    }

    /**
     * Sets country_is_not
     *
     * @param string[]|null $country_is_not Excluded countries
     *
     * @return self
     */
    public function setCountryIsNot($country_is_not)
    {
        if (is_null($country_is_not)) {
            throw new \InvalidArgumentException('non-nullable country_is_not cannot be null');
        }
        $this->container['country_is_not'] = $country_is_not;

        return $this;
    }

    /**
     * Gets method
     *
     * @return string|null
     */
    public function getMethod()
    {
        return $this->container['method'];
    }

    /**
     * Sets method
     *
     * @param string|null $method Method filter type (method_is, method_is_not, any)
     *
     * @return self
     */
    public function setMethod($method)
    {
        if (is_null($method)) {
            throw new \InvalidArgumentException('non-nullable method cannot be null');
        }
        $this->container['method'] = $method;

        return $this;
    }

    /**
     * Gets method_is
     *
     * @return string[]|null
     */
    public function getMethodIs()
    {
        return $this->container['method_is'];
    }

    /**
     * Sets method_is
     *
     * @param string[]|null $method_is Allowed HTTP methods
     *
     * @return self
     */
    public function setMethodIs($method_is)
    {
        if (is_null($method_is)) {
            throw new \InvalidArgumentException('non-nullable method_is cannot be null');
        }
        $this->container['method_is'] = $method_is;

        return $this;
    }

    /**
     * Gets method_is_not
     *
     * @return string[]|null
     */
    public function getMethodIsNot()
    {
        return $this->container['method_is_not'];
    }

    /**
     * Sets method_is_not
     *
     * @param string[]|null $method_is_not Excluded HTTP methods
     *
     * @return self
     */
    public function setMethodIsNot($method_is_not)
    {
        if (is_null($method_is_not)) {
            throw new \InvalidArgumentException('non-nullable method_is_not cannot be null');
        }
        $this->container['method_is_not'] = $method_is_not;

        return $this;
    }

    /**
     * Gets ip
     *
     * @return string|null
     */
    public function getIp()
    {
        return $this->container['ip'];
    }

    /**
     * Sets ip
     *
     * @param string|null $ip IP filter type (ip_is, ip_is_not, any)
     *
     * @return self
     */
    public function setIp($ip)
    {
        if (is_null($ip)) {
            throw new \InvalidArgumentException('non-nullable ip cannot be null');
        }
        $this->container['ip'] = $ip;

        return $this;
    }

    /**
     * Gets ip_is
     *
     * @return string[]|null
     */
    public function getIpIs()
    {
        return $this->container['ip_is'];
    }

    /**
     * Sets ip_is
     *
     * @param string[]|null $ip_is Allowed IP addresses
     *
     * @return self
     */
    public function setIpIs($ip_is)
    {
        if (is_null($ip_is)) {
            throw new \InvalidArgumentException('non-nullable ip_is cannot be null');
        }
        $this->container['ip_is'] = $ip_is;

        return $this;
    }

    /**
     * Gets ip_is_not
     *
     * @return string[]|null
     */
    public function getIpIsNot()
    {
        return $this->container['ip_is_not'];
    }

    /**
     * Sets ip_is_not
     *
     * @param string[]|null $ip_is_not Excluded IP addresses
     *
     * @return self
     */
    public function setIpIsNot($ip_is_not)
    {
        if (is_null($ip_is_not)) {
            throw new \InvalidArgumentException('non-nullable ip_is_not cannot be null');
        }
        $this->container['ip_is_not'] = $ip_is_not;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string $to Target URL to proxy to
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string|null
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string|null $host Host header override
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            throw new \InvalidArgumentException('non-nullable host cannot be null');
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets auth_user
     *
     * @return string|null
     */
    public function getAuthUser()
    {
        return $this->container['auth_user'];
    }

    /**
     * Sets auth_user
     *
     * @param string|null $auth_user Basic auth username
     *
     * @return self
     */
    public function setAuthUser($auth_user)
    {
        if (is_null($auth_user)) {
            throw new \InvalidArgumentException('non-nullable auth_user cannot be null');
        }
        $this->container['auth_user'] = $auth_user;

        return $this;
    }

    /**
     * Gets auth_pass
     *
     * @return string|null
     */
    public function getAuthPass()
    {
        return $this->container['auth_pass'];
    }

    /**
     * Sets auth_pass
     *
     * @param string|null $auth_pass Basic auth password
     *
     * @return self
     */
    public function setAuthPass($auth_pass)
    {
        if (is_null($auth_pass)) {
            throw new \InvalidArgumentException('non-nullable auth_pass cannot be null');
        }
        $this->container['auth_pass'] = $auth_pass;

        return $this;
    }

    /**
     * Gets disable_ssl_verify
     *
     * @return bool|null
     */
    public function getDisableSslVerify()
    {
        return $this->container['disable_ssl_verify'];
    }

    /**
     * Sets disable_ssl_verify
     *
     * @param bool|null $disable_ssl_verify Disable SSL verification
     *
     * @return self
     */
    public function setDisableSslVerify($disable_ssl_verify)
    {
        if (is_null($disable_ssl_verify)) {
            throw new \InvalidArgumentException('non-nullable disable_ssl_verify cannot be null');
        }
        $this->container['disable_ssl_verify'] = $disable_ssl_verify;

        return $this;
    }

    /**
     * Gets cache_lifetime
     *
     * @return string|null
     */
    public function getCacheLifetime()
    {
        return $this->container['cache_lifetime'];
    }

    /**
     * Sets cache_lifetime
     *
     * @param string|null $cache_lifetime Cache lifetime
     *
     * @return self
     */
    public function setCacheLifetime($cache_lifetime)
    {
        if (is_null($cache_lifetime)) {
            array_push($this->openAPINullablesSetToNull, 'cache_lifetime');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cache_lifetime', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cache_lifetime'] = $cache_lifetime;

        return $this;
    }

    /**
     * Gets only_proxy_404
     *
     * @return bool|null
     */
    public function getOnlyProxy404()
    {
        return $this->container['only_proxy_404'];
    }

    /**
     * Sets only_proxy_404
     *
     * @param bool|null $only_proxy_404 Only proxy 404 responses
     *
     * @return self
     */
    public function setOnlyProxy404($only_proxy_404)
    {
        if (is_null($only_proxy_404)) {
            throw new \InvalidArgumentException('non-nullable only_proxy_404 cannot be null');
        }
        $this->container['only_proxy_404'] = $only_proxy_404;

        return $this;
    }

    /**
     * Gets inject_headers
     *
     * @return array<string,string>|null
     */
    public function getInjectHeaders()
    {
        return $this->container['inject_headers'];
    }

    /**
     * Sets inject_headers
     *
     * @param array<string,string>|null $inject_headers Headers to inject
     *
     * @return self
     */
    public function setInjectHeaders($inject_headers)
    {
        if (is_null($inject_headers)) {
            array_push($this->openAPINullablesSetToNull, 'inject_headers');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('inject_headers', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['inject_headers'] = $inject_headers;

        return $this;
    }

    /**
     * Gets proxy_strip_headers
     *
     * @return string[]|null
     */
    public function getProxyStripHeaders()
    {
        return $this->container['proxy_strip_headers'];
    }

    /**
     * Sets proxy_strip_headers
     *
     * @param string[]|null $proxy_strip_headers Headers to strip from response
     *
     * @return self
     */
    public function setProxyStripHeaders($proxy_strip_headers)
    {
        if (is_null($proxy_strip_headers)) {
            throw new \InvalidArgumentException('non-nullable proxy_strip_headers cannot be null');
        }
        $this->container['proxy_strip_headers'] = $proxy_strip_headers;

        return $this;
    }

    /**
     * Gets proxy_strip_request_headers
     *
     * @return string[]|null
     */
    public function getProxyStripRequestHeaders()
    {
        return $this->container['proxy_strip_request_headers'];
    }

    /**
     * Sets proxy_strip_request_headers
     *
     * @param string[]|null $proxy_strip_request_headers Headers to strip from request
     *
     * @return self
     */
    public function setProxyStripRequestHeaders($proxy_strip_request_headers)
    {
        if (is_null($proxy_strip_request_headers)) {
            throw new \InvalidArgumentException('non-nullable proxy_strip_request_headers cannot be null');
        }
        $this->container['proxy_strip_request_headers'] = $proxy_strip_request_headers;

        return $this;
    }

    /**
     * Gets origin_timeout
     *
     * @return string|null
     */
    public function getOriginTimeout()
    {
        return $this->container['origin_timeout'];
    }

    /**
     * Sets origin_timeout
     *
     * @param string|null $origin_timeout Origin timeout
     *
     * @return self
     */
    public function setOriginTimeout($origin_timeout)
    {
        if (is_null($origin_timeout)) {
            throw new \InvalidArgumentException('non-nullable origin_timeout cannot be null');
        }
        $this->container['origin_timeout'] = $origin_timeout;

        return $this;
    }

    /**
     * Gets failover_mode
     *
     * @return bool|null
     */
    public function getFailoverMode()
    {
        return $this->container['failover_mode'];
    }

    /**
     * Sets failover_mode
     *
     * @param bool|null $failover_mode Enable failover mode
     *
     * @return self
     */
    public function setFailoverMode($failover_mode)
    {
        if (is_null($failover_mode)) {
            throw new \InvalidArgumentException('non-nullable failover_mode cannot be null');
        }
        $this->container['failover_mode'] = $failover_mode;

        return $this;
    }

    /**
     * Gets failover_origin_ttfb
     *
     * @return string|null
     */
    public function getFailoverOriginTtfb()
    {
        return $this->container['failover_origin_ttfb'];
    }

    /**
     * Sets failover_origin_ttfb
     *
     * @param string|null $failover_origin_ttfb Failover TTFB threshold in milliseconds
     *
     * @return self
     */
    public function setFailoverOriginTtfb($failover_origin_ttfb)
    {
        if (is_null($failover_origin_ttfb)) {
            throw new \InvalidArgumentException('non-nullable failover_origin_ttfb cannot be null');
        }
        $this->container['failover_origin_ttfb'] = $failover_origin_ttfb;

        return $this;
    }

    /**
     * Gets failover_origin_status_codes
     *
     * @return string[]|null
     */
    public function getFailoverOriginStatusCodes()
    {
        return $this->container['failover_origin_status_codes'];
    }

    /**
     * Sets failover_origin_status_codes
     *
     * @param string[]|null $failover_origin_status_codes Origin status codes that trigger failover
     *
     * @return self
     */
    public function setFailoverOriginStatusCodes($failover_origin_status_codes)
    {
        if (is_null($failover_origin_status_codes)) {
            throw new \InvalidArgumentException('non-nullable failover_origin_status_codes cannot be null');
        }
        $this->container['failover_origin_status_codes'] = $failover_origin_status_codes;

        return $this;
    }

    /**
     * Gets failover_lifetime
     *
     * @return string|null
     */
    public function getFailoverLifetime()
    {
        return $this->container['failover_lifetime'];
    }

    /**
     * Sets failover_lifetime
     *
     * @param string|null $failover_lifetime Failover cache lifetime in seconds
     *
     * @return self
     */
    public function setFailoverLifetime($failover_lifetime)
    {
        if (is_null($failover_lifetime)) {
            throw new \InvalidArgumentException('non-nullable failover_lifetime cannot be null');
        }
        $this->container['failover_lifetime'] = $failover_lifetime;

        return $this;
    }

    /**
     * Gets proxy_alert_enabled
     *
     * @return bool|null
     */
    public function getProxyAlertEnabled()
    {
        return $this->container['proxy_alert_enabled'];
    }

    /**
     * Sets proxy_alert_enabled
     *
     * @param bool|null $proxy_alert_enabled Proxy alert enabled
     *
     * @return self
     */
    public function setProxyAlertEnabled($proxy_alert_enabled)
    {
        if (is_null($proxy_alert_enabled)) {
            throw new \InvalidArgumentException('non-nullable proxy_alert_enabled cannot be null');
        }
        $this->container['proxy_alert_enabled'] = $proxy_alert_enabled;

        return $this;
    }

    /**
     * Gets waf_enabled
     *
     * @return bool|null
     */
    public function getWafEnabled()
    {
        return $this->container['waf_enabled'];
    }

    /**
     * Sets waf_enabled
     *
     * @param bool|null $waf_enabled WAF enabled
     *
     * @return self
     */
    public function setWafEnabled($waf_enabled)
    {
        if (is_null($waf_enabled)) {
            throw new \InvalidArgumentException('non-nullable waf_enabled cannot be null');
        }
        $this->container['waf_enabled'] = $waf_enabled;

        return $this;
    }

    /**
     * Gets waf_config
     *
     * @return \QuantClient\Model\WafConfig|null
     */
    public function getWafConfig()
    {
        return $this->container['waf_config'];
    }

    /**
     * Sets waf_config
     *
     * @param \QuantClient\Model\WafConfig|null $waf_config waf_config
     *
     * @return self
     */
    public function setWafConfig($waf_config)
    {
        if (is_null($waf_config)) {
            array_push($this->openAPINullablesSetToNull, 'waf_config');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('waf_config', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['waf_config'] = $waf_config;

        return $this;
    }

    /**
     * Gets application_proxy
     *
     * @return bool|null
     */
    public function getApplicationProxy()
    {
        return $this->container['application_proxy'];
    }

    /**
     * Sets application_proxy
     *
     * @param bool|null $application_proxy Enable Quant Cloud application proxy mode
     *
     * @return self
     */
    public function setApplicationProxy($application_proxy)
    {
        if (is_null($application_proxy)) {
            throw new \InvalidArgumentException('non-nullable application_proxy cannot be null');
        }
        $this->container['application_proxy'] = $application_proxy;

        return $this;
    }

    /**
     * Gets application_name
     *
     * @return string|null
     */
    public function getApplicationName()
    {
        return $this->container['application_name'];
    }

    /**
     * Sets application_name
     *
     * @param string|null $application_name Quant Cloud application name (required when application_proxy is true)
     *
     * @return self
     */
    public function setApplicationName($application_name)
    {
        if (is_null($application_name)) {
            throw new \InvalidArgumentException('non-nullable application_name cannot be null');
        }
        $this->container['application_name'] = $application_name;

        return $this;
    }

    /**
     * Gets application_environment
     *
     * @return string|null
     */
    public function getApplicationEnvironment()
    {
        return $this->container['application_environment'];
    }

    /**
     * Sets application_environment
     *
     * @param string|null $application_environment Quant Cloud application environment (required when application_proxy is true)
     *
     * @return self
     */
    public function setApplicationEnvironment($application_environment)
    {
        if (is_null($application_environment)) {
            throw new \InvalidArgumentException('non-nullable application_environment cannot be null');
        }
        $this->container['application_environment'] = $application_environment;

        return $this;
    }

    /**
     * Gets application_container
     *
     * @return string|null
     */
    public function getApplicationContainer()
    {
        return $this->container['application_container'];
    }

    /**
     * Sets application_container
     *
     * @param string|null $application_container Quant Cloud application container (required when application_proxy is true)
     *
     * @return self
     */
    public function setApplicationContainer($application_container)
    {
        if (is_null($application_container)) {
            throw new \InvalidArgumentException('non-nullable application_container cannot be null');
        }
        $this->container['application_container'] = $application_container;

        return $this;
    }

    /**
     * Gets application_port
     *
     * @return int|null
     */
    public function getApplicationPort()
    {
        return $this->container['application_port'];
    }

    /**
     * Sets application_port
     *
     * @param int|null $application_port Quant Cloud application port (required when application_proxy is true)
     *
     * @return self
     */
    public function setApplicationPort($application_port)
    {
        if (is_null($application_port)) {
            throw new \InvalidArgumentException('non-nullable application_port cannot be null');
        }
        $this->container['application_port'] = $application_port;

        return $this;
    }

    /**
     * Gets static_error_page
     *
     * @return string|null
     */
    public function getStaticErrorPage()
    {
        return $this->container['static_error_page'];
    }

    /**
     * Sets static_error_page
     *
     * @param string|null $static_error_page Static error page content (HTML) to serve on origin errors
     *
     * @return self
     */
    public function setStaticErrorPage($static_error_page)
    {
        if (is_null($static_error_page)) {
            array_push($this->openAPINullablesSetToNull, 'static_error_page');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('static_error_page', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['static_error_page'] = $static_error_page;

        return $this;
    }

    /**
     * Gets static_error_page_status_codes
     *
     * @return string[]|null
     */
    public function getStaticErrorPageStatusCodes()
    {
        return $this->container['static_error_page_status_codes'];
    }

    /**
     * Sets static_error_page_status_codes
     *
     * @param string[]|null $static_error_page_status_codes Origin status codes that trigger static error page
     *
     * @return self
     */
    public function setStaticErrorPageStatusCodes($static_error_page_status_codes)
    {
        if (is_null($static_error_page_status_codes)) {
            throw new \InvalidArgumentException('non-nullable static_error_page_status_codes cannot be null');
        }
        $this->container['static_error_page_status_codes'] = $static_error_page_status_codes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


