<?php
/**
 * Volume
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.12.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace QuantClient\Model;

use \ArrayAccess;
use \QuantClient\ObjectSerializer;

/**
 * Volume Class Doc Comment
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Volume implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Volume';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'volume_id' => 'string',
        'volume_name' => 'string',
        'description' => 'string',
        'environment_efs_id' => 'string',
        'created_at' => 'string',
        'root_directory' => 'string',
        'access_point_id' => 'string',
        'access_point_arn' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'volume_id' => null,
        'volume_name' => null,
        'description' => null,
        'environment_efs_id' => null,
        'created_at' => null,
        'root_directory' => null,
        'access_point_id' => null,
        'access_point_arn' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'volume_id' => false,
        'volume_name' => false,
        'description' => false,
        'environment_efs_id' => false,
        'created_at' => false,
        'root_directory' => false,
        'access_point_id' => false,
        'access_point_arn' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'volume_id' => 'volumeId',
        'volume_name' => 'volumeName',
        'description' => 'description',
        'environment_efs_id' => 'environmentEfsId',
        'created_at' => 'createdAt',
        'root_directory' => 'rootDirectory',
        'access_point_id' => 'accessPointId',
        'access_point_arn' => 'accessPointArn'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'volume_id' => 'setVolumeId',
        'volume_name' => 'setVolumeName',
        'description' => 'setDescription',
        'environment_efs_id' => 'setEnvironmentEfsId',
        'created_at' => 'setCreatedAt',
        'root_directory' => 'setRootDirectory',
        'access_point_id' => 'setAccessPointId',
        'access_point_arn' => 'setAccessPointArn'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'volume_id' => 'getVolumeId',
        'volume_name' => 'getVolumeName',
        'description' => 'getDescription',
        'environment_efs_id' => 'getEnvironmentEfsId',
        'created_at' => 'getCreatedAt',
        'root_directory' => 'getRootDirectory',
        'access_point_id' => 'getAccessPointId',
        'access_point_arn' => 'getAccessPointArn'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('volume_id', $data ?? [], null);
        $this->setIfExists('volume_name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('environment_efs_id', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('root_directory', $data ?? [], null);
        $this->setIfExists('access_point_id', $data ?? [], null);
        $this->setIfExists('access_point_arn', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets volume_id
     *
     * @return string|null
     */
    public function getVolumeId()
    {
        return $this->container['volume_id'];
    }

    /**
     * Sets volume_id
     *
     * @param string|null $volume_id volume_id
     *
     * @return self
     */
    public function setVolumeId($volume_id)
    {
        if (is_null($volume_id)) {
            throw new \InvalidArgumentException('non-nullable volume_id cannot be null');
        }
        $this->container['volume_id'] = $volume_id;

        return $this;
    }

    /**
     * Gets volume_name
     *
     * @return string|null
     */
    public function getVolumeName()
    {
        return $this->container['volume_name'];
    }

    /**
     * Sets volume_name
     *
     * @param string|null $volume_name volume_name
     *
     * @return self
     */
    public function setVolumeName($volume_name)
    {
        if (is_null($volume_name)) {
            throw new \InvalidArgumentException('non-nullable volume_name cannot be null');
        }
        $this->container['volume_name'] = $volume_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets environment_efs_id
     *
     * @return string|null
     */
    public function getEnvironmentEfsId()
    {
        return $this->container['environment_efs_id'];
    }

    /**
     * Sets environment_efs_id
     *
     * @param string|null $environment_efs_id environment_efs_id
     *
     * @return self
     */
    public function setEnvironmentEfsId($environment_efs_id)
    {
        if (is_null($environment_efs_id)) {
            throw new \InvalidArgumentException('non-nullable environment_efs_id cannot be null');
        }
        $this->container['environment_efs_id'] = $environment_efs_id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets root_directory
     *
     * @return string|null
     */
    public function getRootDirectory()
    {
        return $this->container['root_directory'];
    }

    /**
     * Sets root_directory
     *
     * @param string|null $root_directory root_directory
     *
     * @return self
     */
    public function setRootDirectory($root_directory)
    {
        if (is_null($root_directory)) {
            throw new \InvalidArgumentException('non-nullable root_directory cannot be null');
        }
        $this->container['root_directory'] = $root_directory;

        return $this;
    }

    /**
     * Gets access_point_id
     *
     * @return string|null
     */
    public function getAccessPointId()
    {
        return $this->container['access_point_id'];
    }

    /**
     * Sets access_point_id
     *
     * @param string|null $access_point_id access_point_id
     *
     * @return self
     */
    public function setAccessPointId($access_point_id)
    {
        if (is_null($access_point_id)) {
            throw new \InvalidArgumentException('non-nullable access_point_id cannot be null');
        }
        $this->container['access_point_id'] = $access_point_id;

        return $this;
    }

    /**
     * Gets access_point_arn
     *
     * @return string|null
     */
    public function getAccessPointArn()
    {
        return $this->container['access_point_arn'];
    }

    /**
     * Sets access_point_arn
     *
     * @param string|null $access_point_arn access_point_arn
     *
     * @return self
     */
    public function setAccessPointArn($access_point_arn)
    {
        if (is_null($access_point_arn)) {
            throw new \InvalidArgumentException('non-nullable access_point_arn cannot be null');
        }
        $this->container['access_point_arn'] = $access_point_arn;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


