<?php
/**
 * WafConfigHttpbl
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.19.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace QuantClient\Model;

use \ArrayAccess;
use \QuantClient\ObjectSerializer;

/**
 * WafConfigHttpbl Class Doc Comment
 *
 * @category Class
 * @description Project Honey Pot HTTP:BL configuration
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WafConfigHttpbl implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WafConfig_httpbl';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'httpbl_enabled' => 'bool',
        'block_suspicious' => 'bool',
        'block_harvester' => 'bool',
        'block_spam' => 'bool',
        'block_search_engine' => 'bool',
        'httpbl_key' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'httpbl_enabled' => null,
        'block_suspicious' => null,
        'block_harvester' => null,
        'block_spam' => null,
        'block_search_engine' => null,
        'httpbl_key' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'httpbl_enabled' => false,
        'block_suspicious' => false,
        'block_harvester' => false,
        'block_spam' => false,
        'block_search_engine' => false,
        'httpbl_key' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'httpbl_enabled' => 'httpbl_enabled',
        'block_suspicious' => 'block_suspicious',
        'block_harvester' => 'block_harvester',
        'block_spam' => 'block_spam',
        'block_search_engine' => 'block_search_engine',
        'httpbl_key' => 'httpbl_key'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'httpbl_enabled' => 'setHttpblEnabled',
        'block_suspicious' => 'setBlockSuspicious',
        'block_harvester' => 'setBlockHarvester',
        'block_spam' => 'setBlockSpam',
        'block_search_engine' => 'setBlockSearchEngine',
        'httpbl_key' => 'setHttpblKey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'httpbl_enabled' => 'getHttpblEnabled',
        'block_suspicious' => 'getBlockSuspicious',
        'block_harvester' => 'getBlockHarvester',
        'block_spam' => 'getBlockSpam',
        'block_search_engine' => 'getBlockSearchEngine',
        'httpbl_key' => 'getHttpblKey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('httpbl_enabled', $data ?? [], false);
        $this->setIfExists('block_suspicious', $data ?? [], false);
        $this->setIfExists('block_harvester', $data ?? [], false);
        $this->setIfExists('block_spam', $data ?? [], false);
        $this->setIfExists('block_search_engine', $data ?? [], false);
        $this->setIfExists('httpbl_key', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets httpbl_enabled
     *
     * @return bool|null
     */
    public function getHttpblEnabled()
    {
        return $this->container['httpbl_enabled'];
    }

    /**
     * Sets httpbl_enabled
     *
     * @param bool|null $httpbl_enabled Enable HTTP:BL
     *
     * @return self
     */
    public function setHttpblEnabled($httpbl_enabled)
    {
        if (is_null($httpbl_enabled)) {
            throw new \InvalidArgumentException('non-nullable httpbl_enabled cannot be null');
        }
        $this->container['httpbl_enabled'] = $httpbl_enabled;

        return $this;
    }

    /**
     * Gets block_suspicious
     *
     * @return bool|null
     */
    public function getBlockSuspicious()
    {
        return $this->container['block_suspicious'];
    }

    /**
     * Sets block_suspicious
     *
     * @param bool|null $block_suspicious Block suspicious IPs
     *
     * @return self
     */
    public function setBlockSuspicious($block_suspicious)
    {
        if (is_null($block_suspicious)) {
            throw new \InvalidArgumentException('non-nullable block_suspicious cannot be null');
        }
        $this->container['block_suspicious'] = $block_suspicious;

        return $this;
    }

    /**
     * Gets block_harvester
     *
     * @return bool|null
     */
    public function getBlockHarvester()
    {
        return $this->container['block_harvester'];
    }

    /**
     * Sets block_harvester
     *
     * @param bool|null $block_harvester Block email harvesters
     *
     * @return self
     */
    public function setBlockHarvester($block_harvester)
    {
        if (is_null($block_harvester)) {
            throw new \InvalidArgumentException('non-nullable block_harvester cannot be null');
        }
        $this->container['block_harvester'] = $block_harvester;

        return $this;
    }

    /**
     * Gets block_spam
     *
     * @return bool|null
     */
    public function getBlockSpam()
    {
        return $this->container['block_spam'];
    }

    /**
     * Sets block_spam
     *
     * @param bool|null $block_spam Block spam sources
     *
     * @return self
     */
    public function setBlockSpam($block_spam)
    {
        if (is_null($block_spam)) {
            throw new \InvalidArgumentException('non-nullable block_spam cannot be null');
        }
        $this->container['block_spam'] = $block_spam;

        return $this;
    }

    /**
     * Gets block_search_engine
     *
     * @return bool|null
     */
    public function getBlockSearchEngine()
    {
        return $this->container['block_search_engine'];
    }

    /**
     * Sets block_search_engine
     *
     * @param bool|null $block_search_engine Block search engines
     *
     * @return self
     */
    public function setBlockSearchEngine($block_search_engine)
    {
        if (is_null($block_search_engine)) {
            throw new \InvalidArgumentException('non-nullable block_search_engine cannot be null');
        }
        $this->container['block_search_engine'] = $block_search_engine;

        return $this;
    }

    /**
     * Gets httpbl_key
     *
     * @return string|null
     */
    public function getHttpblKey()
    {
        return $this->container['httpbl_key'];
    }

    /**
     * Sets httpbl_key
     *
     * @param string|null $httpbl_key HTTP:BL API key
     *
     * @return self
     */
    public function setHttpblKey($httpbl_key)
    {
        if (is_null($httpbl_key)) {
            throw new \InvalidArgumentException('non-nullable httpbl_key cannot be null');
        }
        $this->container['httpbl_key'] = $httpbl_key;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


