<?php
/**
 * ComposeApi
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.15.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace QuantClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use QuantClient\ApiException;
use QuantClient\Configuration;
use QuantClient\FormDataProcessor;
use QuantClient\HeaderSelector;
use QuantClient\ObjectSerializer;

/**
 * ComposeApi Class Doc Comment
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ComposeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getEnvironmentCompose' => [
            'application/json',
        ],
        'patchEnvironmentCompose' => [
            'application/json',
        ],
        'validateCompose' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getEnvironmentCompose
     *
     * Get the compose file for an environment
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \QuantClient\Model\Compose
     */
    public function getEnvironmentCompose($organisation, $application, $environment, string $contentType = self::contentTypes['getEnvironmentCompose'][0])
    {
        list($response) = $this->getEnvironmentComposeWithHttpInfo($organisation, $application, $environment, $contentType);
        return $response;
    }

    /**
     * Operation getEnvironmentComposeWithHttpInfo
     *
     * Get the compose file for an environment
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \QuantClient\Model\Compose, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEnvironmentComposeWithHttpInfo($organisation, $application, $environment, string $contentType = self::contentTypes['getEnvironmentCompose'][0])
    {
        $request = $this->getEnvironmentComposeRequest($organisation, $application, $environment, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\QuantClient\Model\Compose',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\QuantClient\Model\Compose',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QuantClient\Model\Compose',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getEnvironmentComposeAsync
     *
     * Get the compose file for an environment
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEnvironmentComposeAsync($organisation, $application, $environment, string $contentType = self::contentTypes['getEnvironmentCompose'][0])
    {
        return $this->getEnvironmentComposeAsyncWithHttpInfo($organisation, $application, $environment, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEnvironmentComposeAsyncWithHttpInfo
     *
     * Get the compose file for an environment
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEnvironmentComposeAsyncWithHttpInfo($organisation, $application, $environment, string $contentType = self::contentTypes['getEnvironmentCompose'][0])
    {
        $returnType = '\QuantClient\Model\Compose';
        $request = $this->getEnvironmentComposeRequest($organisation, $application, $environment, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEnvironmentCompose'
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEnvironmentComposeRequest($organisation, $application, $environment, string $contentType = self::contentTypes['getEnvironmentCompose'][0])
    {

        // verify the required parameter 'organisation' is set
        if ($organisation === null || (is_array($organisation) && count($organisation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organisation when calling getEnvironmentCompose'
            );
        }

        // verify the required parameter 'application' is set
        if ($application === null || (is_array($application) && count($application) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $application when calling getEnvironmentCompose'
            );
        }

        // verify the required parameter 'environment' is set
        if ($environment === null || (is_array($environment) && count($environment) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $environment when calling getEnvironmentCompose'
            );
        }


        $resourcePath = '/api/v3/organizations/{organisation}/applications/{application}/environments/{environment}/compose';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organisation !== null) {
            $resourcePath = str_replace(
                '{' . 'organisation' . '}',
                ObjectSerializer::toPathValue($organisation),
                $resourcePath
            );
        }
        // path params
        if ($application !== null) {
            $resourcePath = str_replace(
                '{' . 'application' . '}',
                ObjectSerializer::toPathValue($application),
                $resourcePath
            );
        }
        // path params
        if ($environment !== null) {
            $resourcePath = str_replace(
                '{' . 'environment' . '}',
                ObjectSerializer::toPathValue($environment),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchEnvironmentCompose
     *
     * Partially Update Environment Compose Definition
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  \QuantClient\Model\PatchEnvironmentComposeRequest $patch_environment_compose_request Partial compose definition updates. All fields are optional. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \QuantClient\Model\PatchEnvironmentCompose202Response|\QuantClient\Model\PatchEnvironmentCompose400Response
     */
    public function patchEnvironmentCompose($organisation, $application, $environment, $patch_environment_compose_request, string $contentType = self::contentTypes['patchEnvironmentCompose'][0])
    {
        list($response) = $this->patchEnvironmentComposeWithHttpInfo($organisation, $application, $environment, $patch_environment_compose_request, $contentType);
        return $response;
    }

    /**
     * Operation patchEnvironmentComposeWithHttpInfo
     *
     * Partially Update Environment Compose Definition
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  \QuantClient\Model\PatchEnvironmentComposeRequest $patch_environment_compose_request Partial compose definition updates. All fields are optional. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \QuantClient\Model\PatchEnvironmentCompose202Response|\QuantClient\Model\PatchEnvironmentCompose400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchEnvironmentComposeWithHttpInfo($organisation, $application, $environment, $patch_environment_compose_request, string $contentType = self::contentTypes['patchEnvironmentCompose'][0])
    {
        $request = $this->patchEnvironmentComposeRequest($organisation, $application, $environment, $patch_environment_compose_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\QuantClient\Model\PatchEnvironmentCompose202Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\QuantClient\Model\PatchEnvironmentCompose400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\QuantClient\Model\PatchEnvironmentCompose202Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QuantClient\Model\PatchEnvironmentCompose202Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QuantClient\Model\PatchEnvironmentCompose400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation patchEnvironmentComposeAsync
     *
     * Partially Update Environment Compose Definition
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  \QuantClient\Model\PatchEnvironmentComposeRequest $patch_environment_compose_request Partial compose definition updates. All fields are optional. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchEnvironmentComposeAsync($organisation, $application, $environment, $patch_environment_compose_request, string $contentType = self::contentTypes['patchEnvironmentCompose'][0])
    {
        return $this->patchEnvironmentComposeAsyncWithHttpInfo($organisation, $application, $environment, $patch_environment_compose_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchEnvironmentComposeAsyncWithHttpInfo
     *
     * Partially Update Environment Compose Definition
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  \QuantClient\Model\PatchEnvironmentComposeRequest $patch_environment_compose_request Partial compose definition updates. All fields are optional. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchEnvironmentComposeAsyncWithHttpInfo($organisation, $application, $environment, $patch_environment_compose_request, string $contentType = self::contentTypes['patchEnvironmentCompose'][0])
    {
        $returnType = '\QuantClient\Model\PatchEnvironmentCompose202Response';
        $request = $this->patchEnvironmentComposeRequest($organisation, $application, $environment, $patch_environment_compose_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchEnvironmentCompose'
     *
     * @param  string $organisation The organisation ID (required)
     * @param  string $application The application ID (required)
     * @param  string $environment The environment ID (required)
     * @param  \QuantClient\Model\PatchEnvironmentComposeRequest $patch_environment_compose_request Partial compose definition updates. All fields are optional. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchEnvironmentCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchEnvironmentComposeRequest($organisation, $application, $environment, $patch_environment_compose_request, string $contentType = self::contentTypes['patchEnvironmentCompose'][0])
    {

        // verify the required parameter 'organisation' is set
        if ($organisation === null || (is_array($organisation) && count($organisation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organisation when calling patchEnvironmentCompose'
            );
        }

        // verify the required parameter 'application' is set
        if ($application === null || (is_array($application) && count($application) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $application when calling patchEnvironmentCompose'
            );
        }

        // verify the required parameter 'environment' is set
        if ($environment === null || (is_array($environment) && count($environment) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $environment when calling patchEnvironmentCompose'
            );
        }

        // verify the required parameter 'patch_environment_compose_request' is set
        if ($patch_environment_compose_request === null || (is_array($patch_environment_compose_request) && count($patch_environment_compose_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $patch_environment_compose_request when calling patchEnvironmentCompose'
            );
        }


        $resourcePath = '/api/v3/organizations/{organisation}/applications/{application}/environments/{environment}/compose';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organisation !== null) {
            $resourcePath = str_replace(
                '{' . 'organisation' . '}',
                ObjectSerializer::toPathValue($organisation),
                $resourcePath
            );
        }
        // path params
        if ($application !== null) {
            $resourcePath = str_replace(
                '{' . 'application' . '}',
                ObjectSerializer::toPathValue($application),
                $resourcePath
            );
        }
        // path params
        if ($environment !== null) {
            $resourcePath = str_replace(
                '{' . 'environment' . '}',
                ObjectSerializer::toPathValue($environment),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($patch_environment_compose_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($patch_environment_compose_request));
            } else {
                $httpBody = $patch_environment_compose_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation validateCompose
     *
     * Validate a compose file
     *
     * @param  string $organisation The organisation ID (required)
     * @param  \QuantClient\Model\ValidateComposeRequest $validate_compose_request The docker-compose.yml file content. Can be sent as raw YAML string or as a JSON wrapper containing both yamlContent (string) and imageSuffix (string) fields. Query parameter imageSuffix takes precedence if both are provided. (required)
     * @param  string|null $image_suffix Optional. Image tag suffix to apply during translation. Transforms internal image tags to consistent &#39;{containerName}-{suffix}&#39; format (e.g., &#39;nginx-pr-456&#39;). External images are left unchanged. Useful for feature branch deployments. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateCompose'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \QuantClient\Model\ValidateCompose200Response|\QuantClient\Model\ValidateCompose422Response
     */
    public function validateCompose($organisation, $validate_compose_request, $image_suffix = null, string $contentType = self::contentTypes['validateCompose'][0])
    {
        list($response) = $this->validateComposeWithHttpInfo($organisation, $validate_compose_request, $image_suffix, $contentType);
        return $response;
    }

    /**
     * Operation validateComposeWithHttpInfo
     *
     * Validate a compose file
     *
     * @param  string $organisation The organisation ID (required)
     * @param  \QuantClient\Model\ValidateComposeRequest $validate_compose_request The docker-compose.yml file content. Can be sent as raw YAML string or as a JSON wrapper containing both yamlContent (string) and imageSuffix (string) fields. Query parameter imageSuffix takes precedence if both are provided. (required)
     * @param  string|null $image_suffix Optional. Image tag suffix to apply during translation. Transforms internal image tags to consistent &#39;{containerName}-{suffix}&#39; format (e.g., &#39;nginx-pr-456&#39;). External images are left unchanged. Useful for feature branch deployments. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateCompose'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \QuantClient\Model\ValidateCompose200Response|\QuantClient\Model\ValidateCompose422Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateComposeWithHttpInfo($organisation, $validate_compose_request, $image_suffix = null, string $contentType = self::contentTypes['validateCompose'][0])
    {
        $request = $this->validateComposeRequest($organisation, $validate_compose_request, $image_suffix, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\QuantClient\Model\ValidateCompose200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\QuantClient\Model\ValidateCompose422Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\QuantClient\Model\ValidateCompose200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QuantClient\Model\ValidateCompose200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QuantClient\Model\ValidateCompose422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation validateComposeAsync
     *
     * Validate a compose file
     *
     * @param  string $organisation The organisation ID (required)
     * @param  \QuantClient\Model\ValidateComposeRequest $validate_compose_request The docker-compose.yml file content. Can be sent as raw YAML string or as a JSON wrapper containing both yamlContent (string) and imageSuffix (string) fields. Query parameter imageSuffix takes precedence if both are provided. (required)
     * @param  string|null $image_suffix Optional. Image tag suffix to apply during translation. Transforms internal image tags to consistent &#39;{containerName}-{suffix}&#39; format (e.g., &#39;nginx-pr-456&#39;). External images are left unchanged. Useful for feature branch deployments. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateComposeAsync($organisation, $validate_compose_request, $image_suffix = null, string $contentType = self::contentTypes['validateCompose'][0])
    {
        return $this->validateComposeAsyncWithHttpInfo($organisation, $validate_compose_request, $image_suffix, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateComposeAsyncWithHttpInfo
     *
     * Validate a compose file
     *
     * @param  string $organisation The organisation ID (required)
     * @param  \QuantClient\Model\ValidateComposeRequest $validate_compose_request The docker-compose.yml file content. Can be sent as raw YAML string or as a JSON wrapper containing both yamlContent (string) and imageSuffix (string) fields. Query parameter imageSuffix takes precedence if both are provided. (required)
     * @param  string|null $image_suffix Optional. Image tag suffix to apply during translation. Transforms internal image tags to consistent &#39;{containerName}-{suffix}&#39; format (e.g., &#39;nginx-pr-456&#39;). External images are left unchanged. Useful for feature branch deployments. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateComposeAsyncWithHttpInfo($organisation, $validate_compose_request, $image_suffix = null, string $contentType = self::contentTypes['validateCompose'][0])
    {
        $returnType = '\QuantClient\Model\ValidateCompose200Response';
        $request = $this->validateComposeRequest($organisation, $validate_compose_request, $image_suffix, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateCompose'
     *
     * @param  string $organisation The organisation ID (required)
     * @param  \QuantClient\Model\ValidateComposeRequest $validate_compose_request The docker-compose.yml file content. Can be sent as raw YAML string or as a JSON wrapper containing both yamlContent (string) and imageSuffix (string) fields. Query parameter imageSuffix takes precedence if both are provided. (required)
     * @param  string|null $image_suffix Optional. Image tag suffix to apply during translation. Transforms internal image tags to consistent &#39;{containerName}-{suffix}&#39; format (e.g., &#39;nginx-pr-456&#39;). External images are left unchanged. Useful for feature branch deployments. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateCompose'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function validateComposeRequest($organisation, $validate_compose_request, $image_suffix = null, string $contentType = self::contentTypes['validateCompose'][0])
    {

        // verify the required parameter 'organisation' is set
        if ($organisation === null || (is_array($organisation) && count($organisation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organisation when calling validateCompose'
            );
        }

        // verify the required parameter 'validate_compose_request' is set
        if ($validate_compose_request === null || (is_array($validate_compose_request) && count($validate_compose_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $validate_compose_request when calling validateCompose'
            );
        }

        if ($image_suffix !== null && !preg_match("/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/", $image_suffix)) {
            throw new \InvalidArgumentException("invalid value for \"image_suffix\" when calling ComposeApi.validateCompose, must conform to the pattern /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.");
        }
        

        $resourcePath = '/api/v3/organizations/{organisation}/compose/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $image_suffix,
            'imageSuffix', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($organisation !== null) {
            $resourcePath = str_replace(
                '{' . 'organisation' . '}',
                ObjectSerializer::toPathValue($organisation),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($validate_compose_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($validate_compose_request));
            } else {
                $httpBody = $validate_compose_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
