<?php
/**
 * VariablesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.15.8
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace QuantClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use QuantClient\ApiException;
use QuantClient\Configuration;
use QuantClient\FormDataProcessor;
use QuantClient\HeaderSelector;
use QuantClient\ObjectSerializer;

/**
 * VariablesApi Class Doc Comment
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VariablesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'bulkSetEnvironmentVariables' => [
            'application/json',
        ],
        'deleteEnvironmentVariable' => [
            'application/json',
        ],
        'listEnvironmentVariables' => [
            'application/json',
        ],
        'updateEnvironmentVariable' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bulkSetEnvironmentVariables
     *
     * Bulk set/replace environment variables
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  \QuantClient\Model\BulkSetEnvironmentVariablesRequest $bulk_set_environment_variables_request bulk_set_environment_variables_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bulkSetEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function bulkSetEnvironmentVariables($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, string $contentType = self::contentTypes['bulkSetEnvironmentVariables'][0])
    {
        $this->bulkSetEnvironmentVariablesWithHttpInfo($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, $contentType);
    }

    /**
     * Operation bulkSetEnvironmentVariablesWithHttpInfo
     *
     * Bulk set/replace environment variables
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  \QuantClient\Model\BulkSetEnvironmentVariablesRequest $bulk_set_environment_variables_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bulkSetEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function bulkSetEnvironmentVariablesWithHttpInfo($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, string $contentType = self::contentTypes['bulkSetEnvironmentVariables'][0])
    {
        $request = $this->bulkSetEnvironmentVariablesRequest($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation bulkSetEnvironmentVariablesAsync
     *
     * Bulk set/replace environment variables
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  \QuantClient\Model\BulkSetEnvironmentVariablesRequest $bulk_set_environment_variables_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bulkSetEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bulkSetEnvironmentVariablesAsync($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, string $contentType = self::contentTypes['bulkSetEnvironmentVariables'][0])
    {
        return $this->bulkSetEnvironmentVariablesAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bulkSetEnvironmentVariablesAsyncWithHttpInfo
     *
     * Bulk set/replace environment variables
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  \QuantClient\Model\BulkSetEnvironmentVariablesRequest $bulk_set_environment_variables_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bulkSetEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bulkSetEnvironmentVariablesAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, string $contentType = self::contentTypes['bulkSetEnvironmentVariables'][0])
    {
        $returnType = '';
        $request = $this->bulkSetEnvironmentVariablesRequest($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bulkSetEnvironmentVariables'
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  \QuantClient\Model\BulkSetEnvironmentVariablesRequest $bulk_set_environment_variables_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bulkSetEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function bulkSetEnvironmentVariablesRequest($api_organisation, $api_application, $api_environment, $bulk_set_environment_variables_request, string $contentType = self::contentTypes['bulkSetEnvironmentVariables'][0])
    {

        // verify the required parameter 'api_organisation' is set
        if ($api_organisation === null || (is_array($api_organisation) && count($api_organisation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_organisation when calling bulkSetEnvironmentVariables'
            );
        }

        // verify the required parameter 'api_application' is set
        if ($api_application === null || (is_array($api_application) && count($api_application) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_application when calling bulkSetEnvironmentVariables'
            );
        }

        // verify the required parameter 'api_environment' is set
        if ($api_environment === null || (is_array($api_environment) && count($api_environment) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_environment when calling bulkSetEnvironmentVariables'
            );
        }

        // verify the required parameter 'bulk_set_environment_variables_request' is set
        if ($bulk_set_environment_variables_request === null || (is_array($bulk_set_environment_variables_request) && count($bulk_set_environment_variables_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bulk_set_environment_variables_request when calling bulkSetEnvironmentVariables'
            );
        }


        $resourcePath = '/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($api_organisation !== null) {
            $resourcePath = str_replace(
                '{' . 'api_organisation' . '}',
                ObjectSerializer::toPathValue($api_organisation),
                $resourcePath
            );
        }
        // path params
        if ($api_application !== null) {
            $resourcePath = str_replace(
                '{' . 'api_application' . '}',
                ObjectSerializer::toPathValue($api_application),
                $resourcePath
            );
        }
        // path params
        if ($api_environment !== null) {
            $resourcePath = str_replace(
                '{' . 'api_environment' . '}',
                ObjectSerializer::toPathValue($api_environment),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($bulk_set_environment_variables_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($bulk_set_environment_variables_request));
            } else {
                $httpBody = $bulk_set_environment_variables_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteEnvironmentVariable
     *
     * Delete a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteEnvironmentVariable($api_organisation, $api_application, $api_environment, $api_variable, string $contentType = self::contentTypes['deleteEnvironmentVariable'][0])
    {
        $this->deleteEnvironmentVariableWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, $contentType);
    }

    /**
     * Operation deleteEnvironmentVariableWithHttpInfo
     *
     * Delete a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteEnvironmentVariableWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, string $contentType = self::contentTypes['deleteEnvironmentVariable'][0])
    {
        $request = $this->deleteEnvironmentVariableRequest($api_organisation, $api_application, $api_environment, $api_variable, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteEnvironmentVariableAsync
     *
     * Delete a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteEnvironmentVariableAsync($api_organisation, $api_application, $api_environment, $api_variable, string $contentType = self::contentTypes['deleteEnvironmentVariable'][0])
    {
        return $this->deleteEnvironmentVariableAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteEnvironmentVariableAsyncWithHttpInfo
     *
     * Delete a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteEnvironmentVariableAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, string $contentType = self::contentTypes['deleteEnvironmentVariable'][0])
    {
        $returnType = '';
        $request = $this->deleteEnvironmentVariableRequest($api_organisation, $api_application, $api_environment, $api_variable, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteEnvironmentVariable'
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteEnvironmentVariableRequest($api_organisation, $api_application, $api_environment, $api_variable, string $contentType = self::contentTypes['deleteEnvironmentVariable'][0])
    {

        // verify the required parameter 'api_organisation' is set
        if ($api_organisation === null || (is_array($api_organisation) && count($api_organisation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_organisation when calling deleteEnvironmentVariable'
            );
        }

        // verify the required parameter 'api_application' is set
        if ($api_application === null || (is_array($api_application) && count($api_application) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_application when calling deleteEnvironmentVariable'
            );
        }

        // verify the required parameter 'api_environment' is set
        if ($api_environment === null || (is_array($api_environment) && count($api_environment) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_environment when calling deleteEnvironmentVariable'
            );
        }

        // verify the required parameter 'api_variable' is set
        if ($api_variable === null || (is_array($api_variable) && count($api_variable) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_variable when calling deleteEnvironmentVariable'
            );
        }


        $resourcePath = '/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables/{api_variable}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($api_organisation !== null) {
            $resourcePath = str_replace(
                '{' . 'api_organisation' . '}',
                ObjectSerializer::toPathValue($api_organisation),
                $resourcePath
            );
        }
        // path params
        if ($api_application !== null) {
            $resourcePath = str_replace(
                '{' . 'api_application' . '}',
                ObjectSerializer::toPathValue($api_application),
                $resourcePath
            );
        }
        // path params
        if ($api_environment !== null) {
            $resourcePath = str_replace(
                '{' . 'api_environment' . '}',
                ObjectSerializer::toPathValue($api_environment),
                $resourcePath
            );
        }
        // path params
        if ($api_variable !== null) {
            $resourcePath = str_replace(
                '{' . 'api_variable' . '}',
                ObjectSerializer::toPathValue($api_variable),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listEnvironmentVariables
     *
     * Get all variables for an environment
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function listEnvironmentVariables($api_organisation, $api_application, $api_environment, string $contentType = self::contentTypes['listEnvironmentVariables'][0])
    {
        $this->listEnvironmentVariablesWithHttpInfo($api_organisation, $api_application, $api_environment, $contentType);
    }

    /**
     * Operation listEnvironmentVariablesWithHttpInfo
     *
     * Get all variables for an environment
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function listEnvironmentVariablesWithHttpInfo($api_organisation, $api_application, $api_environment, string $contentType = self::contentTypes['listEnvironmentVariables'][0])
    {
        $request = $this->listEnvironmentVariablesRequest($api_organisation, $api_application, $api_environment, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation listEnvironmentVariablesAsync
     *
     * Get all variables for an environment
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEnvironmentVariablesAsync($api_organisation, $api_application, $api_environment, string $contentType = self::contentTypes['listEnvironmentVariables'][0])
    {
        return $this->listEnvironmentVariablesAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listEnvironmentVariablesAsyncWithHttpInfo
     *
     * Get all variables for an environment
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEnvironmentVariablesAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, string $contentType = self::contentTypes['listEnvironmentVariables'][0])
    {
        $returnType = '';
        $request = $this->listEnvironmentVariablesRequest($api_organisation, $api_application, $api_environment, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listEnvironmentVariables'
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listEnvironmentVariables'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listEnvironmentVariablesRequest($api_organisation, $api_application, $api_environment, string $contentType = self::contentTypes['listEnvironmentVariables'][0])
    {

        // verify the required parameter 'api_organisation' is set
        if ($api_organisation === null || (is_array($api_organisation) && count($api_organisation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_organisation when calling listEnvironmentVariables'
            );
        }

        // verify the required parameter 'api_application' is set
        if ($api_application === null || (is_array($api_application) && count($api_application) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_application when calling listEnvironmentVariables'
            );
        }

        // verify the required parameter 'api_environment' is set
        if ($api_environment === null || (is_array($api_environment) && count($api_environment) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_environment when calling listEnvironmentVariables'
            );
        }


        $resourcePath = '/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($api_organisation !== null) {
            $resourcePath = str_replace(
                '{' . 'api_organisation' . '}',
                ObjectSerializer::toPathValue($api_organisation),
                $resourcePath
            );
        }
        // path params
        if ($api_application !== null) {
            $resourcePath = str_replace(
                '{' . 'api_application' . '}',
                ObjectSerializer::toPathValue($api_application),
                $resourcePath
            );
        }
        // path params
        if ($api_environment !== null) {
            $resourcePath = str_replace(
                '{' . 'api_environment' . '}',
                ObjectSerializer::toPathValue($api_environment),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateEnvironmentVariable
     *
     * Update a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  \QuantClient\Model\UpdateEnvironmentVariableRequest $update_environment_variable_request update_environment_variable_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateEnvironmentVariable($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, string $contentType = self::contentTypes['updateEnvironmentVariable'][0])
    {
        $this->updateEnvironmentVariableWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, $contentType);
    }

    /**
     * Operation updateEnvironmentVariableWithHttpInfo
     *
     * Update a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  \QuantClient\Model\UpdateEnvironmentVariableRequest $update_environment_variable_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \QuantClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateEnvironmentVariableWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, string $contentType = self::contentTypes['updateEnvironmentVariable'][0])
    {
        $request = $this->updateEnvironmentVariableRequest($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateEnvironmentVariableAsync
     *
     * Update a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  \QuantClient\Model\UpdateEnvironmentVariableRequest $update_environment_variable_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateEnvironmentVariableAsync($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, string $contentType = self::contentTypes['updateEnvironmentVariable'][0])
    {
        return $this->updateEnvironmentVariableAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateEnvironmentVariableAsyncWithHttpInfo
     *
     * Update a variable
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  \QuantClient\Model\UpdateEnvironmentVariableRequest $update_environment_variable_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateEnvironmentVariableAsyncWithHttpInfo($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, string $contentType = self::contentTypes['updateEnvironmentVariable'][0])
    {
        $returnType = '';
        $request = $this->updateEnvironmentVariableRequest($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateEnvironmentVariable'
     *
     * @param  string $api_organisation The organisation ID (required)
     * @param  string $api_application The application ID (required)
     * @param  string $api_environment The environment ID (required)
     * @param  string $api_variable The variable key (required)
     * @param  \QuantClient\Model\UpdateEnvironmentVariableRequest $update_environment_variable_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEnvironmentVariable'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateEnvironmentVariableRequest($api_organisation, $api_application, $api_environment, $api_variable, $update_environment_variable_request, string $contentType = self::contentTypes['updateEnvironmentVariable'][0])
    {

        // verify the required parameter 'api_organisation' is set
        if ($api_organisation === null || (is_array($api_organisation) && count($api_organisation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_organisation when calling updateEnvironmentVariable'
            );
        }

        // verify the required parameter 'api_application' is set
        if ($api_application === null || (is_array($api_application) && count($api_application) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_application when calling updateEnvironmentVariable'
            );
        }

        // verify the required parameter 'api_environment' is set
        if ($api_environment === null || (is_array($api_environment) && count($api_environment) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_environment when calling updateEnvironmentVariable'
            );
        }

        // verify the required parameter 'api_variable' is set
        if ($api_variable === null || (is_array($api_variable) && count($api_variable) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_variable when calling updateEnvironmentVariable'
            );
        }

        // verify the required parameter 'update_environment_variable_request' is set
        if ($update_environment_variable_request === null || (is_array($update_environment_variable_request) && count($update_environment_variable_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_environment_variable_request when calling updateEnvironmentVariable'
            );
        }


        $resourcePath = '/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables/{api_variable}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($api_organisation !== null) {
            $resourcePath = str_replace(
                '{' . 'api_organisation' . '}',
                ObjectSerializer::toPathValue($api_organisation),
                $resourcePath
            );
        }
        // path params
        if ($api_application !== null) {
            $resourcePath = str_replace(
                '{' . 'api_application' . '}',
                ObjectSerializer::toPathValue($api_application),
                $resourcePath
            );
        }
        // path params
        if ($api_environment !== null) {
            $resourcePath = str_replace(
                '{' . 'api_environment' . '}',
                ObjectSerializer::toPathValue($api_environment),
                $resourcePath
            );
        }
        // path params
        if ($api_variable !== null) {
            $resourcePath = str_replace(
                '{' . 'api_variable' . '}',
                ObjectSerializer::toPathValue($api_variable),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_environment_variable_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_environment_variable_request));
            } else {
                $httpBody = $update_environment_variable_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
