<?php
/**
 * CreateApplicationRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\CreateApplicationRequest;

/**
 * CreateApplicationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateApplicationRequest
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateApplicationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateApplicationRequest"
     */
    public function testCreateApplicationRequest()
    {
        $model = new CreateApplicationRequest();
        $this->assertInstanceOf(CreateApplicationRequest::class, $model);
    }

    /**
     * Test attribute "app_name"
     */
    public function testPropertyAppName()
    {
        $model = new CreateApplicationRequest();
        $this->assertInstanceOf(CreateApplicationRequest::class, $model);
    }

    /**
     * Test attribute "compose_definition"
     */
    public function testPropertyComposeDefinition()
    {
        $model = new CreateApplicationRequest();
        $this->assertInstanceOf(CreateApplicationRequest::class, $model);
    }

    /**
     * Test attribute "min_capacity"
     */
    public function testPropertyMinCapacity()
    {
        $model = new CreateApplicationRequest();
        $this->assertInstanceOf(CreateApplicationRequest::class, $model);
    }

    /**
     * Test attribute "max_capacity"
     */
    public function testPropertyMaxCapacity()
    {
        $model = new CreateApplicationRequest();
        $this->assertInstanceOf(CreateApplicationRequest::class, $model);
    }

    /**
     * Test attribute "database"
     */
    public function testPropertyDatabase()
    {
        $model = new CreateApplicationRequest();
        $this->assertInstanceOf(CreateApplicationRequest::class, $model);
    }

    /**
     * Test attribute "filesystem"
     */
    public function testPropertyFilesystem()
    {
        $model = new CreateApplicationRequest();
        $this->assertInstanceOf(CreateApplicationRequest::class, $model);
    }
}
