<?php
/**
 * GetSshAccessCredentials200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\GetSshAccessCredentials200Response;

/**
 * GetSshAccessCredentials200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetSshAccessCredentials200Response
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetSshAccessCredentials200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetSshAccessCredentials200Response"
     */
    public function testGetSshAccessCredentials200Response()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "credentials"
     */
    public function testPropertyCredentials()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "cluster_name"
     */
    public function testPropertyClusterName()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "task_arn"
     */
    public function testPropertyTaskArn()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "container_names"
     */
    public function testPropertyContainerNames()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "expires_in"
     */
    public function testPropertyExpiresIn()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }

    /**
     * Test attribute "organization_scope"
     */
    public function testPropertyOrganizationScope()
    {
        $model = new GetSshAccessCredentials200Response();
        $this->assertInstanceOf(GetSshAccessCredentials200Response::class, $model);
    }
}
