<?php
/**
 * ListToolExecutions200ResponseExecutionsInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListToolExecutions200ResponseExecutionsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ListToolExecutions200ResponseExecutionsInner
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListToolExecutions200ResponseExecutionsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListToolExecutions200ResponseExecutionsInner"
     */
    public function testListToolExecutions200ResponseExecutionsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "execution_id"
     */
    public function testPropertyExecutionId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tool_name"
     */
    public function testPropertyToolName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "completed_at"
     */
    public function testPropertyCompletedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
