<?php
/**
 * ListToolExecutions200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\ListToolExecutions200Response;

/**
 * ListToolExecutions200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ListToolExecutions200Response
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListToolExecutions200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListToolExecutions200Response"
     */
    public function testListToolExecutions200Response()
    {
        $model = new ListToolExecutions200Response();
        $this->assertInstanceOf(ListToolExecutions200Response::class, $model);
    }

    /**
     * Test attribute "executions"
     */
    public function testPropertyExecutions()
    {
        $model = new ListToolExecutions200Response();
        $this->assertInstanceOf(ListToolExecutions200Response::class, $model);
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
        $model = new ListToolExecutions200Response();
        $this->assertInstanceOf(ListToolExecutions200Response::class, $model);
    }

    /**
     * Test attribute "org_id"
     */
    public function testPropertyOrgId()
    {
        $model = new ListToolExecutions200Response();
        $this->assertInstanceOf(ListToolExecutions200Response::class, $model);
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $model = new ListToolExecutions200Response();
        $this->assertInstanceOf(ListToolExecutions200Response::class, $model);
    }
}
