<?php
/**
 * V1ContentRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\V1ContentRequest;

/**
 * V1ContentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description V1ContentRequest
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1ContentRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1ContentRequest"
     */
    public function testV1ContentRequest()
    {
        $model = new V1ContentRequest();
        $this->assertInstanceOf(V1ContentRequest::class, $model);
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
        $model = new V1ContentRequest();
        $this->assertInstanceOf(V1ContentRequest::class, $model);
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
        $model = new V1ContentRequest();
        $this->assertInstanceOf(V1ContentRequest::class, $model);
    }

    /**
     * Test attribute "published"
     */
    public function testPropertyPublished()
    {
        $model = new V1ContentRequest();
        $this->assertInstanceOf(V1ContentRequest::class, $model);
    }

    /**
     * Test attribute "content_timestamp"
     */
    public function testPropertyContentTimestamp()
    {
        $model = new V1ContentRequest();
        $this->assertInstanceOf(V1ContentRequest::class, $model);
    }

    /**
     * Test attribute "info"
     */
    public function testPropertyInfo()
    {
        $model = new V1ContentRequest();
        $this->assertInstanceOf(V1ContentRequest::class, $model);
    }

    /**
     * Test attribute "transitions"
     */
    public function testPropertyTransitions()
    {
        $model = new V1ContentRequest();
        $this->assertInstanceOf(V1ContentRequest::class, $model);
    }
}
