<?php
/**
 * V1MetricMonthStatsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\V1MetricMonthStats;

/**
 * V1MetricMonthStatsTest Class Doc Comment
 *
 * @category    Class
 * @description V1MetricMonthStats
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1MetricMonthStatsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1MetricMonthStats"
     */
    public function testV1MetricMonthStats()
    {
        $model = new V1MetricMonthStats();
        $this->assertInstanceOf(V1MetricMonthStats::class, $model);
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
        $model = new V1MetricMonthStats();
        $this->assertInstanceOf(V1MetricMonthStats::class, $model);
    }

    /**
     * Test attribute "month_total"
     */
    public function testPropertyMonthTotal()
    {
        $model = new V1MetricMonthStats();
        $this->assertInstanceOf(V1MetricMonthStats::class, $model);
    }

    /**
     * Test attribute "month_series"
     */
    public function testPropertyMonthSeries()
    {
        $model = new V1MetricMonthStats();
        $this->assertInstanceOf(V1MetricMonthStats::class, $model);
    }

    /**
     * Test attribute "month_average"
     */
    public function testPropertyMonthAverage()
    {
        $model = new V1MetricMonthStats();
        $this->assertInstanceOf(V1MetricMonthStats::class, $model);
    }
}
