<?php
/**
 * V2ProjectRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\V2ProjectRequest;

/**
 * V2ProjectRequestTest Class Doc Comment
 *
 * @category    Class
 * @description V2ProjectRequest
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V2ProjectRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V2ProjectRequest"
     */
    public function testV2ProjectRequest()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "machine_name"
     */
    public function testPropertyMachineName()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "allow_query_params"
     */
    public function testPropertyAllowQueryParams()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "disable_revisions"
     */
    public function testPropertyDisableRevisions()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "basic_auth_username"
     */
    public function testPropertyBasicAuthUsername()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "basic_auth_password"
     */
    public function testPropertyBasicAuthPassword()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }

    /**
     * Test attribute "basic_auth_preview_only"
     */
    public function testPropertyBasicAuthPreviewOnly()
    {
        $model = new V2ProjectRequest();
        $this->assertInstanceOf(V2ProjectRequest::class, $model);
    }
}
