<?php
/**
 * WafConfigHttpblTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\WafConfigHttpbl;

/**
 * WafConfigHttpblTest Class Doc Comment
 *
 * @category    Class
 * @description Project Honey Pot HTTP:BL configuration
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WafConfigHttpblTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WafConfigHttpbl"
     */
    public function testWafConfigHttpbl()
    {
        $model = new WafConfigHttpbl();
        $this->assertInstanceOf(WafConfigHttpbl::class, $model);
    }

    /**
     * Test attribute "httpbl_enabled"
     */
    public function testPropertyHttpblEnabled()
    {
        $model = new WafConfigHttpbl();
        $this->assertInstanceOf(WafConfigHttpbl::class, $model);
    }

    /**
     * Test attribute "block_suspicious"
     */
    public function testPropertyBlockSuspicious()
    {
        $model = new WafConfigHttpbl();
        $this->assertInstanceOf(WafConfigHttpbl::class, $model);
    }

    /**
     * Test attribute "block_harvester"
     */
    public function testPropertyBlockHarvester()
    {
        $model = new WafConfigHttpbl();
        $this->assertInstanceOf(WafConfigHttpbl::class, $model);
    }

    /**
     * Test attribute "block_spam"
     */
    public function testPropertyBlockSpam()
    {
        $model = new WafConfigHttpbl();
        $this->assertInstanceOf(WafConfigHttpbl::class, $model);
    }

    /**
     * Test attribute "block_search_engine"
     */
    public function testPropertyBlockSearchEngine()
    {
        $model = new WafConfigHttpbl();
        $this->assertInstanceOf(WafConfigHttpbl::class, $model);
    }

    /**
     * Test attribute "httpbl_key"
     */
    public function testPropertyHttpblKey()
    {
        $model = new WafConfigHttpbl();
        $this->assertInstanceOf(WafConfigHttpbl::class, $model);
    }
}
