<?php
/**
 * WafConfigBlockListsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  QuantClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * QuantCDN API
 *
 * Unified API for QuantCDN Admin and QuantCloud Platform services
 *
 * The version of the OpenAPI document: 4.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace QuantClient\Test\Model;

use PHPUnit\Framework\TestCase;
use QuantClient\Model\WafConfigBlockLists;

/**
 * WafConfigBlockListsTest Class Doc Comment
 *
 * @category    Class
 * @description Enable predefined block lists
 * @package     QuantClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WafConfigBlockListsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WafConfigBlockLists"
     */
    public function testWafConfigBlockLists()
    {
        $model = new WafConfigBlockLists();
        $this->assertInstanceOf(WafConfigBlockLists::class, $model);
    }

    /**
     * Test attribute "user_agent"
     */
    public function testPropertyUserAgent()
    {
        $model = new WafConfigBlockLists();
        $this->assertInstanceOf(WafConfigBlockLists::class, $model);
    }

    /**
     * Test attribute "referer"
     */
    public function testPropertyReferer()
    {
        $model = new WafConfigBlockLists();
        $this->assertInstanceOf(WafConfigBlockLists::class, $model);
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
        $model = new WafConfigBlockLists();
        $this->assertInstanceOf(WafConfigBlockLists::class, $model);
    }

    /**
     * Test attribute "ai"
     */
    public function testPropertyAi()
    {
        $model = new WafConfigBlockLists();
        $this->assertInstanceOf(WafConfigBlockLists::class, $model);
    }
}
